__report = {
  summary: {
    total: { eslint: 32, sloc: 2316, maintainability: 2276.8469999999998 },
    average: { sloc: 72, maintainability: "71.15", eslint: "1.00" },
  },
  reports: [
    {
      info: {
        file: "src/env.js",
        fileShort: "env.js",
        fileSafe: "env_js",
        link: "files/env_js/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 6.897,
          halstead: {
            bugs: 0.229,
            difficulty: 14.52,
            effort: 9983.952,
            length: 133,
            time: 554.664,
            vocabulary: 36,
            volume: 687.6,
            operands: {
              distinct: 25,
              total: 66,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 11,
              total: 67,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 29, physical: 57 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 6.897,
            halstead: {
              bugs: 0.229,
              difficulty: 14.52,
              effort: 9983.952,
              length: 133,
              time: 554.664,
              vocabulary: 36,
              volume: 687.6,
              operands: {
                distinct: 25,
                total: 66,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 11,
                total: 67,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 29, physical: 57 },
          },
        },
        module: "env.js",
        maintainability: 49.276,
      },
    },
    {
      info: {
        file: "src/app/layout.tsx",
        fileShort: "app/layout.tsx",
        fileSafe: "app_layout_tsx",
        link: "files/app_layout_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 13.333,
          halstead: {
            bugs: 0.113,
            difficulty: 6.387,
            effort: 2169.799,
            length: 63,
            time: 120.544,
            vocabulary: 42,
            volume: 339.716,
            operands: {
              distinct: 31,
              total: 36,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 11,
              total: 27,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 1,
          sloc: { logical: 15, physical: 61 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 13.333,
            halstead: {
              bugs: 0.113,
              difficulty: 6.387,
              effort: 2169.799,
              length: 63,
              time: 120.544,
              vocabulary: 42,
              volume: 339.716,
              operands: {
                distinct: 31,
                total: 36,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 11,
                total: 27,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 1,
            sloc: { logical: 15, physical: 61 },
          },
        },
        module: "app/layout.tsx",
        maintainability: 66.933,
      },
    },
    {
      info: {
        file: "src/app/page.tsx",
        fileShort: "app/page.tsx",
        fileSafe: "app_page_tsx",
        link: "files/app_page_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 3,
          cyclomaticDensity: 50,
          halstead: {
            bugs: 0.039,
            difficulty: 3.563,
            effort: 413.055,
            length: 26,
            time: 22.947,
            vocabulary: 22,
            volume: 115.945,
            operands: {
              distinct: 16,
              total: 19,
              identifiers: ["__stripped__"],
            },
            operators: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 6, physical: 48 },
          complexity: {
            cyclomatic: 3,
            cyclomaticDensity: 50,
            halstead: {
              bugs: 0.039,
              difficulty: 3.563,
              effort: 413.055,
              length: 26,
              time: 22.947,
              vocabulary: 22,
              volume: 115.945,
              operands: {
                distinct: 16,
                total: 19,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 6,
                total: 7,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 6, physical: 48 },
          },
        },
        module: "app/page.tsx",
        maintainability: 78.694,
      },
    },
    {
      info: {
        file: "src/server/db.ts",
        fileShort: "server/db.ts",
        fileSafe: "server_db_ts",
        link: "files/server_db_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 4,
          cyclomaticDensity: 44.444,
          halstead: {
            bugs: 0.082,
            difficulty: 12.5,
            effort: 3066.807,
            length: 50,
            time: 170.378,
            vocabulary: 30,
            volume: 245.345,
            operands: {
              distinct: 15,
              total: 25,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 15,
              total: 25,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 9, physical: 18 },
          complexity: {
            cyclomatic: 4,
            cyclomaticDensity: 44.444,
            halstead: {
              bugs: 0.082,
              difficulty: 12.5,
              effort: 3066.807,
              length: 50,
              time: 170.378,
              vocabulary: 30,
              volume: 245.345,
              operands: {
                distinct: 15,
                total: 25,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 15,
                total: 25,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 9, physical: 18 },
          },
        },
        module: "server/db.ts",
        maintainability: 70.675,
      },
    },
    {
      info: {
        file: "src/trpc/query-client.ts",
        fileShort: "trpc/query-client.ts",
        fileSafe: "trpc_query_client_ts",
        link: "files/trpc_query_client_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 4,
          cyclomaticDensity: 28.571,
          halstead: {
            bugs: 0.081,
            difficulty: 6.325,
            effort: 1535.429,
            length: 49,
            time: 85.302,
            vocabulary: 31,
            volume: 242.756,
            operands: {
              distinct: 20,
              total: 23,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 11,
              total: 26,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 1,
          sloc: { logical: 14, physical: 26 },
          complexity: {
            cyclomatic: 4,
            cyclomaticDensity: 28.571,
            halstead: {
              bugs: 0.081,
              difficulty: 6.325,
              effort: 1535.429,
              length: 49,
              time: 85.302,
              vocabulary: 31,
              volume: 242.756,
              operands: {
                distinct: 20,
                total: 23,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 11,
                total: 26,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 1,
            sloc: { logical: 14, physical: 26 },
          },
        },
        module: "trpc/query-client.ts",
        maintainability: 72.762,
      },
    },
    {
      info: {
        file: "src/trpc/react.tsx",
        fileShort: "trpc/react.tsx",
        fileSafe: "trpc_react_tsx",
        link: "files/trpc_react_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 12,
          cyclomaticDensity: 29.268,
          halstead: {
            bugs: 0.334,
            difficulty: 18.99,
            effort: 19041.39,
            length: 160,
            time: 1057.855,
            vocabulary: 77,
            volume: 1002.686,
            operands: {
              distinct: 52,
              total: 79,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 25,
              total: 81,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 2,
          sloc: { logical: 41, physical: 79 },
          complexity: {
            cyclomatic: 12,
            cyclomaticDensity: 29.268,
            halstead: {
              bugs: 0.334,
              difficulty: 18.99,
              effort: 19041.39,
              length: 160,
              time: 1057.855,
              vocabulary: 77,
              volume: 1002.686,
              operands: {
                distinct: 52,
                total: 79,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 25,
                total: 81,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 2,
            sloc: { logical: 41, physical: 79 },
          },
        },
        module: "trpc/react.tsx",
        maintainability: 67.122,
      },
    },
    {
      info: {
        file: "src/trpc/server.ts",
        fileShort: "trpc/server.ts",
        fileSafe: "trpc_server_ts",
        link: "files/trpc_server_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 11.765,
          halstead: {
            bugs: 0.081,
            difficulty: 6.5,
            effort: 1576.245,
            length: 51,
            time: 87.569,
            vocabulary: 27,
            volume: 242.499,
            operands: {
              distinct: 18,
              total: 26,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 9,
              total: 25,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 17, physical: 31 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 11.765,
            halstead: {
              bugs: 0.081,
              difficulty: 6.5,
              effort: 1576.245,
              length: 51,
              time: 87.569,
              vocabulary: 27,
              volume: 242.499,
              operands: {
                distinct: 18,
                total: 26,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 9,
                total: 25,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 17, physical: 31 },
          },
        },
        module: "trpc/server.ts",
        maintainability: 66.386,
      },
    },
    {
      info: {
        file: "src/utils/uploadthing.ts",
        fileShort: "utils/uploadthing.ts",
        fileSafe: "utils_uploadthing_ts",
        link: "files/utils_uploadthing_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 1,
          cyclomaticDensity: 14.286,
          halstead: {
            bugs: 0.023,
            difficulty: 2.857,
            effort: 197.682,
            length: 20,
            time: 10.982,
            vocabulary: 11,
            volume: 69.189,
            operands: { distinct: 7, total: 10, identifiers: ["__stripped__"] },
            operators: {
              distinct: 4,
              total: 10,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 7, physical: 13 },
          complexity: {
            cyclomatic: 1,
            cyclomaticDensity: 14.286,
            halstead: {
              bugs: 0.023,
              difficulty: 2.857,
              effort: 197.682,
              length: 20,
              time: 10.982,
              vocabulary: 11,
              volume: 69.189,
              operands: {
                distinct: 7,
                total: 10,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 4,
                total: 10,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 7, physical: 13 },
          },
        },
        module: "utils/uploadthing.ts",
        maintainability: 70.992,
      },
    },
    {
      info: {
        file: "src/app/auth/page.tsx",
        fileShort: "app/auth/page.tsx",
        fileSafe: "app_auth_page_tsx",
        link: "files/app_auth_page_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 3,
          cyclomaticDensity: 50,
          halstead: {
            bugs: 0.017,
            difficulty: 3.5,
            effort: 175.663,
            length: 14,
            time: 9.759,
            vocabulary: 12,
            volume: 50.189,
            operands: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
            operators: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 6, physical: 14 },
          complexity: {
            cyclomatic: 3,
            cyclomaticDensity: 50,
            halstead: {
              bugs: 0.017,
              difficulty: 3.5,
              effort: 175.663,
              length: 14,
              time: 9.759,
              vocabulary: 12,
              volume: 50.189,
              operands: {
                distinct: 6,
                total: 7,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 6,
                total: 7,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 6, physical: 14 },
          },
        },
        module: "app/auth/page.tsx",
        maintainability: 80.404,
      },
    },
    {
      info: {
        file: "src/app/components/LeafletMap.tsx",
        fileShort: "app/components/LeafletMap.tsx",
        fileSafe: "app_components_LeafletMap_tsx",
        link: "files/app_components_LeafletMap_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 40,
          halstead: {
            bugs: 0.037,
            difficulty: 5.318,
            effort: 597.605,
            length: 26,
            time: 33.2,
            vocabulary: 20,
            volume: 112.37,
            operands: {
              distinct: 11,
              total: 13,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 9,
              total: 13,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 5, physical: 22 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 40,
            halstead: {
              bugs: 0.037,
              difficulty: 5.318,
              effort: 597.605,
              length: 26,
              time: 33.2,
              vocabulary: 20,
              volume: 112.37,
              operands: {
                distinct: 11,
                total: 13,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 9,
                total: 13,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 5, physical: 22 },
          },
        },
        module: "app/components/LeafletMap.tsx",
        maintainability: 79.92,
      },
    },
    {
      info: {
        file: "src/app/components/LoadingSpinner.tsx",
        fileShort: "app/components/LoadingSpinner.tsx",
        fileSafe: "app_components_LoadingSpinner_tsx",
        link: "files/app_components_LoadingSpinner_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 3,
          cyclomaticDensity: 100,
          halstead: {
            bugs: 0.032,
            difficulty: 4.038,
            effort: 383.987,
            length: 22,
            time: 21.333,
            vocabulary: 20,
            volume: 95.082,
            operands: {
              distinct: 13,
              total: 15,
              identifiers: ["__stripped__"],
            },
            operators: { distinct: 7, total: 7, identifiers: ["__stripped__"] },
          },
          paramCount: 1,
          sloc: { logical: 3, physical: 18 },
          complexity: {
            cyclomatic: 3,
            cyclomaticDensity: 100,
            halstead: {
              bugs: 0.032,
              difficulty: 4.038,
              effort: 383.987,
              length: 22,
              time: 21.333,
              vocabulary: 20,
              volume: 95.082,
              operands: {
                distinct: 13,
                total: 15,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 7,
                total: 7,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 1,
            sloc: { logical: 3, physical: 18 },
          },
        },
        module: "app/components/LoadingSpinner.tsx",
        maintainability: 85.407,
      },
    },
    {
      info: {
        file: "src/app/components/Navigation.tsx",
        fileShort: "app/components/Navigation.tsx",
        fileSafe: "app_components_Navigation_tsx",
        link: "files/app_components_Navigation_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 7,
          cyclomaticDensity: 58.333,
          halstead: {
            bugs: 0.092,
            difficulty: 8.119,
            effort: 2232.738,
            length: 55,
            time: 124.041,
            vocabulary: 32,
            volume: 275,
            operands: {
              distinct: 21,
              total: 31,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 11,
              total: 24,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 12, physical: 56 },
          complexity: {
            cyclomatic: 7,
            cyclomaticDensity: 58.333,
            halstead: {
              bugs: 0.092,
              difficulty: 8.119,
              effort: 2232.738,
              length: 55,
              time: 124.041,
              vocabulary: 32,
              volume: 275,
              operands: {
                distinct: 21,
                total: 31,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 11,
                total: 24,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 12, physical: 56 },
          },
        },
        module: "app/components/Navigation.tsx",
        maintainability: 73.146,
      },
    },
    {
      info: {
        file: "src/app/components/UploadThingDrop.tsx",
        fileShort: "app/components/UploadThingDrop.tsx",
        fileSafe: "app_components_UploadThingDrop_tsx",
        link: "files/app_components_UploadThingDrop_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 70,
          cyclomaticDensity: 30.303,
          halstead: {
            bugs: 2.6,
            difficulty: 44.633,
            effort: 348190.302,
            length: 992,
            time: 19343.906,
            vocabulary: 233,
            volume: 7801.273,
            operands: {
              distinct: 200,
              total: 541,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 33,
              total: 451,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 21,
          sloc: { logical: 231, physical: 411 },
          complexity: {
            cyclomatic: 70,
            cyclomaticDensity: 30.303,
            halstead: {
              bugs: 2.6,
              difficulty: 44.633,
              effort: 348190.302,
              length: 992,
              time: 19343.906,
              vocabulary: 233,
              volume: 7801.273,
              operands: {
                distinct: 200,
                total: 541,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 33,
                total: 451,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 21,
            sloc: { logical: 231, physical: 411 },
          },
        },
        module: "app/components/UploadThingDrop.tsx",
        maintainability: 60.616,
      },
    },
    {
      info: {
        file: "src/app/ieskoti/page.tsx",
        fileShort: "app/ieskoti/page.tsx",
        fileSafe: "app_ieskoti_page_tsx",
        link: "files/app_ieskoti_page_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 100,
          halstead: {
            bugs: 0.002,
            difficulty: 1,
            effort: 4.755,
            length: 3,
            time: 0.264,
            vocabulary: 3,
            volume: 4.755,
            operands: { distinct: 1, total: 1, identifiers: ["__stripped__"] },
            operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 2, physical: 6 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 100,
            halstead: {
              bugs: 0.002,
              difficulty: 1,
              effort: 4.755,
              length: 3,
              time: 0.264,
              vocabulary: 3,
              volume: 4.755,
              operands: {
                distinct: 1,
                total: 1,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 2,
                total: 2,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 2, physical: 6 },
          },
        },
        module: "app/ieskoti/page.tsx",
        maintainability: 98.268,
      },
    },
    {
      info: {
        file: "src/app/zemelapis/page.tsx",
        fileShort: "app/zemelapis/page.tsx",
        fileSafe: "app_zemelapis_page_tsx",
        link: "files/app_zemelapis_page_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 100,
          halstead: {
            bugs: 0.002,
            difficulty: 1,
            effort: 4.755,
            length: 3,
            time: 0.264,
            vocabulary: 3,
            volume: 4.755,
            operands: { distinct: 1, total: 1, identifiers: ["__stripped__"] },
            operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 2, physical: 6 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 100,
            halstead: {
              bugs: 0.002,
              difficulty: 1,
              effort: 4.755,
              length: 3,
              time: 0.264,
              vocabulary: 3,
              volume: 4.755,
              operands: {
                distinct: 1,
                total: 1,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 2,
                total: 2,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 2, physical: 6 },
          },
        },
        module: "app/zemelapis/page.tsx",
        maintainability: 98.268,
      },
    },
    {
      info: {
        file: "src/server/api/root.ts",
        fileShort: "server/api/root.ts",
        fileSafe: "server_api_root_ts",
        link: "files/server_api_root_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 1,
          cyclomaticDensity: 20,
          halstead: {
            bugs: 0.02,
            difficulty: 3.214,
            effort: 195.893,
            length: 17,
            time: 10.883,
            vocabulary: 12,
            volume: 60.944,
            operands: { distinct: 7, total: 9, identifiers: ["__stripped__"] },
            operators: { distinct: 5, total: 8, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 5, physical: 24 },
          complexity: {
            cyclomatic: 1,
            cyclomaticDensity: 20,
            halstead: {
              bugs: 0.02,
              difficulty: 3.214,
              effort: 195.893,
              length: 17,
              time: 10.883,
              vocabulary: 12,
              volume: 60.944,
              operands: {
                distinct: 7,
                total: 9,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 5,
                total: 8,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 5, physical: 24 },
          },
        },
        module: "server/api/root.ts",
        maintainability: 74.198,
      },
    },
    {
      info: {
        file: "src/server/api/trpc.ts",
        fileShort: "server/api/trpc.ts",
        fileSafe: "server_api_trpc_ts",
        link: "files/server_api_trpc_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 8,
          cyclomaticDensity: 15.094,
          halstead: {
            bugs: 0.442,
            difficulty: 18.393,
            effort: 24362.454,
            length: 212,
            time: 1353.47,
            vocabulary: 76,
            volume: 1324.561,
            operands: {
              distinct: 56,
              total: 103,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 20,
              total: 109,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 6,
          sloc: { logical: 53, physical: 134 },
          complexity: {
            cyclomatic: 8,
            cyclomaticDensity: 15.094,
            halstead: {
              bugs: 0.442,
              difficulty: 18.393,
              effort: 24362.454,
              length: 212,
              time: 1353.47,
              vocabulary: 76,
              volume: 1324.561,
              operands: {
                distinct: 56,
                total: 103,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 20,
                total: 109,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 6,
            sloc: { logical: 53, physical: 134 },
          },
        },
        module: "server/api/trpc.ts",
        maintainability: 60.376,
      },
    },
    {
      info: {
        file: "src/server/auth/config.ts",
        fileShort: "server/auth/config.ts",
        fileSafe: "server_auth_config_ts",
        link: "files/server_auth_config_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 15.385,
          halstead: {
            bugs: 0.1,
            difficulty: 7.071,
            effort: 2116.622,
            length: 61,
            time: 117.59,
            vocabulary: 30,
            volume: 299.32,
            operands: {
              distinct: 21,
              total: 33,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 9,
              total: 28,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 2,
          sloc: { logical: 13, physical: 67 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 15.385,
            halstead: {
              bugs: 0.1,
              difficulty: 7.071,
              effort: 2116.622,
              length: 61,
              time: 117.59,
              vocabulary: 30,
              volume: 299.32,
              operands: {
                distinct: 21,
                total: 33,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 9,
                total: 28,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 2,
            sloc: { logical: 13, physical: 67 },
          },
        },
        module: "server/auth/config.ts",
        maintainability: 68.338,
      },
    },
    {
      info: {
        file: "src/server/auth/index.ts",
        fileShort: "server/auth/index.ts",
        fileSafe: "server_auth_index_ts",
        link: "files/server_auth_index_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 1,
          cyclomaticDensity: 12.5,
          halstead: {
            bugs: 0.026,
            difficulty: 4.063,
            effort: 315.694,
            length: 21,
            time: 17.539,
            vocabulary: 13,
            volume: 77.709,
            operands: { distinct: 8, total: 13, identifiers: ["__stripped__"] },
            operators: { distinct: 5, total: 8, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 8, physical: 11 },
          complexity: {
            cyclomatic: 1,
            cyclomaticDensity: 12.5,
            halstead: {
              bugs: 0.026,
              difficulty: 4.063,
              effort: 315.694,
              length: 21,
              time: 17.539,
              vocabulary: 13,
              volume: 77.709,
              operands: {
                distinct: 8,
                total: 13,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 5,
                total: 8,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 8, physical: 11 },
          },
        },
        module: "server/auth/index.ts",
        maintainability: 68.79,
      },
    },
    {
      info: {
        file: "src/app/api/uploadthing/core.ts",
        fileShort: "app/api/uploadthing/core.ts",
        fileSafe: "app_api_uploadthing_core_ts",
        link: "files/app_api_uploadthing_core_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 16.667,
          halstead: {
            bugs: 0.059,
            difficulty: 4.8,
            effort: 846.811,
            length: 39,
            time: 47.045,
            vocabulary: 23,
            volume: 176.419,
            operands: {
              distinct: 15,
              total: 18,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 8,
              total: 21,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 1,
          sloc: { logical: 12, physical: 35 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 16.667,
            halstead: {
              bugs: 0.059,
              difficulty: 4.8,
              effort: 846.811,
              length: 39,
              time: 47.045,
              vocabulary: 23,
              volume: 176.419,
              operands: {
                distinct: 15,
                total: 18,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 8,
                total: 21,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 1,
            sloc: { logical: 12, physical: 35 },
          },
        },
        module: "app/api/uploadthing/core.ts",
        maintainability: 70.929,
      },
    },
    {
      info: {
        file: "src/app/api/uploadthing/route.ts",
        fileShort: "app/api/uploadthing/route.ts",
        fileSafe: "app_api_uploadthing_route_ts",
        link: "files/app_api_uploadthing_route_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 1,
          cyclomaticDensity: 16.667,
          halstead: {
            bugs: 0.023,
            difficulty: 3.75,
            effort: 256.996,
            length: 18,
            time: 14.278,
            vocabulary: 14,
            volume: 68.532,
            operands: { distinct: 8, total: 10, identifiers: ["__stripped__"] },
            operators: { distinct: 6, total: 8, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 6, physical: 14 },
          complexity: {
            cyclomatic: 1,
            cyclomaticDensity: 16.667,
            halstead: {
              bugs: 0.023,
              difficulty: 3.75,
              effort: 256.996,
              length: 18,
              time: 14.278,
              vocabulary: 14,
              volume: 68.532,
              operands: {
                distinct: 8,
                total: 10,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 6,
                total: 8,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 6, physical: 14 },
          },
        },
        module: "app/api/uploadthing/route.ts",
        maintainability: 71.927,
      },
    },
    {
      info: {
        file: "src/app/components/commonUi/Button.tsx",
        fileShort: "app/components/commonUi/Button.tsx",
        fileSafe: "app_components_commonUi_Button_tsx",
        link: "files/app_components_commonUi_Button_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 8,
          cyclomaticDensity: 25,
          halstead: {
            bugs: 0.454,
            difficulty: 12.25,
            effort: 16700.292,
            length: 210,
            time: 927.794,
            vocabulary: 90,
            volume: 1363.289,
            operands: {
              distinct: 76,
              total: 133,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 14,
              total: 77,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 16,
          sloc: { logical: 32, physical: 119 },
          complexity: {
            cyclomatic: 8,
            cyclomaticDensity: 25,
            halstead: {
              bugs: 0.454,
              difficulty: 12.25,
              effort: 16700.292,
              length: 210,
              time: 927.794,
              vocabulary: 90,
              volume: 1363.289,
              operands: {
                distinct: 76,
                total: 133,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 14,
                total: 77,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 16,
            sloc: { logical: 32, physical: 119 },
          },
        },
        module: "app/components/commonUi/Button.tsx",
        maintainability: 54.863,
      },
    },
    {
      info: {
        file: "src/app/components/interactiveMap/InteractiveMap.tsx",
        fileShort: "app/components/interactiveMap/InteractiveMap.tsx",
        fileSafe: "app_components_interactiveMap_InteractiveMap_tsx",
        link: "files/app_components_interactiveMap_InteractiveMap_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 16,
          cyclomaticDensity: 35.556,
          halstead: {
            bugs: 0.548,
            difficulty: 18.365,
            effort: 30190.692,
            length: 252,
            time: 1677.261,
            vocabulary: 92,
            volume: 1643.938,
            operands: {
              distinct: 74,
              total: 151,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 18,
              total: 101,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 20,
          sloc: { logical: 45, physical: 147 },
          complexity: {
            cyclomatic: 16,
            cyclomaticDensity: 35.556,
            halstead: {
              bugs: 0.548,
              difficulty: 18.365,
              effort: 30190.692,
              length: 252,
              time: 1677.261,
              vocabulary: 92,
              volume: 1643.938,
              operands: {
                distinct: 74,
                total: 151,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 18,
                total: 101,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 20,
            sloc: { logical: 45, physical: 147 },
          },
        },
        module: "app/components/interactiveMap/InteractiveMap.tsx",
        maintainability: 68.18,
      },
    },
    {
      info: {
        file: "src/app/components/interactiveMap/MapBenchMarker.tsx",
        fileShort: "app/components/interactiveMap/MapBenchMarker.tsx",
        fileSafe: "app_components_interactiveMap_MapBenchMarker_tsx",
        link: "files/app_components_interactiveMap_MapBenchMarker_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 4,
          cyclomaticDensity: 30.769,
          halstead: {
            bugs: 0.071,
            difficulty: 7.028,
            effort: 1502.196,
            length: 44,
            time: 83.455,
            vocabulary: 29,
            volume: 213.751,
            operands: {
              distinct: 18,
              total: 23,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 11,
              total: 21,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 1,
          sloc: { logical: 13, physical: 24 },
          complexity: {
            cyclomatic: 4,
            cyclomaticDensity: 30.769,
            halstead: {
              bugs: 0.071,
              difficulty: 7.028,
              effort: 1502.196,
              length: 44,
              time: 83.455,
              vocabulary: 29,
              volume: 213.751,
              operands: {
                distinct: 18,
                total: 23,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 11,
                total: 21,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 1,
            sloc: { logical: 13, physical: 24 },
          },
        },
        module: "app/components/interactiveMap/MapBenchMarker.tsx",
        maintainability: 73.508,
      },
    },
    {
      info: {
        file: "src/app/components/interactiveMap/PostPopup.tsx",
        fileShort: "app/components/interactiveMap/PostPopup.tsx",
        fileSafe: "app_components_interactiveMap_PostPopup_tsx",
        link: "files/app_components_interactiveMap_PostPopup_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 36,
          cyclomaticDensity: 46.154,
          halstead: {
            bugs: 1.094,
            difficulty: 28.912,
            effort: 94921.2,
            length: 456,
            time: 5273.4,
            vocabulary: 147,
            volume: 3283.051,
            operands: {
              distinct: 120,
              total: 257,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 27,
              total: 199,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 9,
          sloc: { logical: 78, physical: 213 },
          complexity: {
            cyclomatic: 36,
            cyclomaticDensity: 46.154,
            halstead: {
              bugs: 1.094,
              difficulty: 28.912,
              effort: 94921.2,
              length: 456,
              time: 5273.4,
              vocabulary: 147,
              volume: 3283.051,
              operands: {
                distinct: 120,
                total: 257,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 27,
                total: 199,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 9,
            sloc: { logical: 78, physical: 213 },
          },
        },
        module: "app/components/interactiveMap/PostPopup.tsx",
        maintainability: 66.364,
      },
    },
    {
      info: {
        file: "src/app/components/interactiveMap/hooks.ts",
        fileShort: "app/components/interactiveMap/hooks.ts",
        fileSafe: "app_components_interactiveMap_hooks_ts",
        link: "files/app_components_interactiveMap_hooks_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 2,
          cyclomaticDensity: 10,
          halstead: {
            bugs: 0.105,
            difficulty: 7.158,
            effort: 2246.309,
            length: 66,
            time: 124.795,
            vocabulary: 27,
            volume: 313.823,
            operands: {
              distinct: 19,
              total: 34,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 8,
              total: 32,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 20, physical: 37 },
          complexity: {
            cyclomatic: 2,
            cyclomaticDensity: 10,
            halstead: {
              bugs: 0.105,
              difficulty: 7.158,
              effort: 2246.309,
              length: 66,
              time: 124.795,
              vocabulary: 27,
              volume: 313.823,
              operands: {
                distinct: 19,
                total: 34,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 8,
                total: 32,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 20, physical: 37 },
          },
        },
        module: "app/components/interactiveMap/hooks.ts",
        maintainability: 64.138,
      },
    },
    {
      info: {
        file: "src/app/components/pages/IeskotiScreen.tsx",
        fileShort: "app/components/pages/IeskotiScreen.tsx",
        fileSafe: "app_components_pages_IeskotiScreen_tsx",
        link: "files/app_components_pages_IeskotiScreen_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 16,
          cyclomaticDensity: 57.143,
          halstead: {
            bugs: 0.275,
            difficulty: 18.012,
            effort: 14834.065,
            length: 140,
            time: 824.115,
            vocabulary: 59,
            volume: 823.57,
            operands: {
              distinct: 42,
              total: 89,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 17,
              total: 51,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 5,
          sloc: { logical: 28, physical: 111 },
          complexity: {
            cyclomatic: 16,
            cyclomaticDensity: 57.143,
            halstead: {
              bugs: 0.275,
              difficulty: 18.012,
              effort: 14834.065,
              length: 140,
              time: 824.115,
              vocabulary: 59,
              volume: 823.57,
              operands: {
                distinct: 42,
                total: 89,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 17,
                total: 51,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 5,
            sloc: { logical: 28, physical: 111 },
          },
        },
        module: "app/components/pages/IeskotiScreen.tsx",
        maintainability: 71.066,
      },
    },
    {
      info: {
        file: "src/app/components/pages/SignInScreen.tsx",
        fileShort: "app/components/pages/SignInScreen.tsx",
        fileSafe: "app_components_pages_SignInScreen_tsx",
        link: "files/app_components_pages_SignInScreen_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 6,
          cyclomaticDensity: 27.273,
          halstead: {
            bugs: 0.114,
            difficulty: 4.667,
            effort: 1591.871,
            length: 65,
            time: 88.437,
            vocabulary: 38,
            volume: 341.115,
            operands: {
              distinct: 30,
              total: 35,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 8,
              total: 30,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 0,
          sloc: { logical: 22, physical: 57 },
          complexity: {
            cyclomatic: 6,
            cyclomaticDensity: 27.273,
            halstead: {
              bugs: 0.114,
              difficulty: 4.667,
              effort: 1591.871,
              length: 65,
              time: 88.437,
              vocabulary: 38,
              volume: 341.115,
              operands: {
                distinct: 30,
                total: 35,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 8,
                total: 30,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 22, physical: 57 },
          },
        },
        module: "app/components/pages/SignInScreen.tsx",
        maintainability: 76.529,
      },
    },
    {
      info: {
        file: "src/app/components/pages/ZemelapisScreen.tsx",
        fileShort: "app/components/pages/ZemelapisScreen.tsx",
        fileSafe: "app_components_pages_ZemelapisScreen_tsx",
        link: "files/app_components_pages_ZemelapisScreen_tsx/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 18,
          cyclomaticDensity: 20,
          halstead: {
            bugs: 0.947,
            difficulty: 25,
            effort: 71062.056,
            length: 416,
            time: 3947.892,
            vocabulary: 114,
            volume: 2842.482,
            operands: {
              distinct: 94,
              total: 235,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 20,
              total: 181,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 4,
          sloc: { logical: 90, physical: 234 },
          complexity: {
            cyclomatic: 18,
            cyclomaticDensity: 20,
            halstead: {
              bugs: 0.947,
              difficulty: 25,
              effort: 71062.056,
              length: 416,
              time: 3947.892,
              vocabulary: 114,
              volume: 2842.482,
              operands: {
                distinct: 94,
                total: 235,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 20,
                total: 181,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 4,
            sloc: { logical: 90, physical: 234 },
          },
        },
        module: "app/components/pages/ZemelapisScreen.tsx",
        maintainability: 54.943,
      },
    },
    {
      info: {
        file: "src/server/api/routers/post.ts",
        fileShort: "server/api/routers/post.ts",
        fileSafe: "server_api_routers_post_ts",
        link: "files/server_api_routers_post_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 22,
          cyclomaticDensity: 13.174,
          halstead: {
            bugs: 1.467,
            difficulty: 32.212,
            effort: 141758.274,
            length: 673,
            time: 7875.46,
            vocabulary: 93,
            volume: 4400.854,
            operands: {
              distinct: 78,
              total: 335,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 15,
              total: 338,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 18,
          sloc: { logical: 167, physical: 184 },
          complexity: {
            cyclomatic: 22,
            cyclomaticDensity: 13.174,
            halstead: {
              bugs: 1.467,
              difficulty: 32.212,
              effort: 141758.274,
              length: 673,
              time: 7875.46,
              vocabulary: 93,
              volume: 4400.854,
              operands: {
                distinct: 78,
                total: 335,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 15,
                total: 338,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 18,
            sloc: { logical: 167, physical: 184 },
          },
        },
        module: "server/api/routers/post.ts",
        maintainability: 57.805,
      },
    },
    {
      info: {
        file: "src/app/api/auth/[...nextauth]/route.ts",
        fileShort: "app/api/auth/[...nextauth]/route.ts",
        fileSafe: "app_api_auth_____nextauth__route_ts",
        link: "files/app_api_auth_____nextauth__route_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 1,
          cyclomaticDensity: 33.333,
          halstead: {
            bugs: 0.007,
            difficulty: 2.5,
            effort: 51.699,
            length: 8,
            time: 2.872,
            vocabulary: 6,
            volume: 20.68,
            operands: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
            operators: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
          },
          paramCount: 0,
          sloc: { logical: 3, physical: 4 },
          complexity: {
            cyclomatic: 1,
            cyclomaticDensity: 33.333,
            halstead: {
              bugs: 0.007,
              difficulty: 2.5,
              effort: 51.699,
              length: 8,
              time: 2.872,
              vocabulary: 6,
              volume: 20.68,
              operands: {
                distinct: 3,
                total: 5,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 3,
                total: 3,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 0,
            sloc: { logical: 3, physical: 4 },
          },
        },
        module: "app/api/auth/[...nextauth]/route.ts",
        maintainability: 81.701,
      },
    },
    {
      info: {
        file: "src/app/api/trpc/[trpc]/route.ts",
        fileShort: "app/api/trpc/[trpc]/route.ts",
        fileSafe: "app_api_trpc__trpc__route_ts",
        link: "files/app_api_trpc__trpc__route_ts/index.html",
      },
      eslint: { messages: 1 },
      complexity: {
        aggregate: {
          cyclomatic: 6,
          cyclomaticDensity: 31.579,
          halstead: {
            bugs: 0.109,
            difficulty: 9.75,
            effort: 3200.673,
            length: 64,
            time: 177.815,
            vocabulary: 35,
            volume: 328.274,
            operands: {
              distinct: 22,
              total: 33,
              identifiers: ["__stripped__"],
            },
            operators: {
              distinct: 13,
              total: 31,
              identifiers: ["__stripped__"],
            },
          },
          paramCount: 4,
          sloc: { logical: 19, physical: 35 },
          complexity: {
            cyclomatic: 6,
            cyclomaticDensity: 31.579,
            halstead: {
              bugs: 0.109,
              difficulty: 9.75,
              effort: 3200.673,
              length: 64,
              time: 177.815,
              vocabulary: 35,
              volume: 328.274,
              operands: {
                distinct: 22,
                total: 33,
                identifiers: ["__stripped__"],
              },
              operators: {
                distinct: 13,
                total: 31,
                identifiers: ["__stripped__"],
              },
            },
            paramCount: 4,
            sloc: { logical: 19, physical: 35 },
          },
        },
        module: "app/api/trpc/[trpc]/route.ts",
        maintainability: 74.323,
      },
    },
  ],
};
